name: Auto-merge Dependabot pull requests

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  call-enable-auto-merge:
    uses: SBence/workflows/.github/workflows/auto-merge-dependabot.yml@master
