name: Build project

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup up Node.js environment
        uses: SBence/setup-node-workflow-yarn@master
        with:
          node-version: "*"

      - name: Downcase repository owner
        run: |
          echo "REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Build project
        run: yarn run build --base=/${{ github.event.repository.name }}/
        env:
          PUBLIC_URL: https://${{ env.REPOSITORY_OWNER }}.github.io/${{ github.event.repository.name }}/
