name: Deploy to Pages

on:
  push:
    branches: [master]
    paths-ignore:
      - ".**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  pages:
    uses: SBence/workflows/.github/workflows/deploy-vite.yml@master
    with:
      node-version: "*"
